#!/bin/ksh
 
set -x

# HOMEdir set in qsub job

. $HOMEdir/jobs/HAFS/JFV3SAR_ENVIR

#. /usrx/local/prod/lmod/lmod/init/ksh
#module purge
#module use ${HOMEgfs}/sorc/fv3gfs.fd/modulefiles/wcoss_dell_p3
#module load fv3
#module load prod_util/1.1.0
#module list

#######################################################################
# Execute the respective BUFR preparation scripts in accordance with
# the user specifications.
#######################################################################

# Create local sub-directories

mkdir -p ${COMROOT}/bufrprep
mkdir -p ${EXPTROOT}/bufrprep

# Process NOAA/AOML/HRD dropsondes with drift calculations.

if [ $PREPBUFRhsa = 1 ]; then
    ${SCRIPTdir}/exfv3sar_bufrprep_hsa.sh
fi
