MACHINE="hera"
ACCOUNT="an_account"
EXPT_SUBDIR="test_community"

PARTITION_DEFAULT="batch"
PARTITION_HPSS="service"
PARTITION_FCST="batch"

QUEUE_DEFAULT="batch"
QUEUE_HPSS="service"
QUEUE_FCST="batch"

VERBOSE="TRUE"

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_CONUS_25km"
GRID_GEN_METHOD="ESGgrid"
QUILTING="TRUE"
CCPP_PHYS_SUITE="FV3_GFS_2017_gfdlmp"
FCST_LEN_HRS="6"
LBC_SPEC_INTVL_HRS="6"

DATE_FIRST_CYCL="20190701"
DATE_LAST_CYCL="20190701"
CYCL_HRS=( "00" )

EXTRN_MDL_NAME_ICS="FV3GFS"
EXTRN_MDL_NAME_LBCS="FV3GFS"

RUN_TASK_MAKE_GRID="TRUE"
RUN_TASK_MAKE_OROG="TRUE"
RUN_TASK_MAKE_SFC_CLIMO="TRUE"

USE_USER_STAGED_EXTRN_FILES="FALSE"

EXTRN_MDL_SOURCE_BASEDIR_ICS="/scratch/ywang/comFV3SAR/testing2/expt_dirs/gfs"
EXTRN_MDL_FILES_ICS=("gfs.t00z.atmanl.nemsio" "gfs.t00z.sfcanl.nemsio")

EXTRN_MDL_SOURCE_BASEDIR_LBCS="/scratch/ywang/comFV3SAR/testing2/expt_dirs/gfs"
EXTRN_MDL_FILES_LBCS=("gfs.t00z.atmf006.nemsio")
